---
title: 异常：invalidArg 函数 (F#)
description: '了解如何为 F # invalidArg 函数生成参数异常。'
ms.date: 05/16/2016
ms.openlocfilehash: 8bf65fae9392a88205e3cdec8b7d7a3ff42f8416
ms.sourcegitcommit: db8b83057d052c1f9f249d128b08d4423af0f7c2
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 11/02/2018
ms.locfileid: "44180314"
---
# <a name="exceptions-the-invalidarg-function"></a><span data-ttu-id="db41f-103">异常：invalidArg 函数</span><span class="sxs-lookup"><span data-stu-id="db41f-103">Exceptions: The invalidArg Function</span></span>

<span data-ttu-id="db41f-104">`invalidArg`函数生成参数异常。</span><span class="sxs-lookup"><span data-stu-id="db41f-104">The `invalidArg` function generates an argument exception.</span></span>

## <a name="syntax"></a><span data-ttu-id="db41f-105">语法</span><span class="sxs-lookup"><span data-stu-id="db41f-105">Syntax</span></span>

```fsharp
invalidArg parameter-name error-message-string
```

## <a name="remarks"></a><span data-ttu-id="db41f-106">备注</span><span class="sxs-lookup"><span data-stu-id="db41f-106">Remarks</span></span>

<span data-ttu-id="db41f-107">在上述语法中的参数名称是参数的其参数是参数的无效名称的字符串。</span><span class="sxs-lookup"><span data-stu-id="db41f-107">The parameter-name in the previous syntax is a string with the name of the parameter whose argument was invalid.</span></span> <span data-ttu-id="db41f-108">*错误消息字符串*是文本字符串或类型的值`string`。</span><span class="sxs-lookup"><span data-stu-id="db41f-108">The *error-message-string* is a literal string or a value of type `string`.</span></span> <span data-ttu-id="db41f-109">它将成为`Message`异常对象的属性。</span><span class="sxs-lookup"><span data-stu-id="db41f-109">It becomes the `Message` property of the exception object.</span></span>

<span data-ttu-id="db41f-110">由生成的异常`invalidArg`是`System.ArgumentException`异常。</span><span class="sxs-lookup"><span data-stu-id="db41f-110">The exception generated by `invalidArg` is a `System.ArgumentException` exception.</span></span> <span data-ttu-id="db41f-111">下面的代码演示如何使用`invalidArg`引发异常。</span><span class="sxs-lookup"><span data-stu-id="db41f-111">The following code illustrates the use of `invalidArg` to throw an exception.</span></span>

[!code-fsharp[Main](../../../../samples/snippets/fsharp/lang-ref-2/snippet6101.fs)]

<span data-ttu-id="db41f-112">输出是以下内容，然后由堆栈跟踪 （未显示）。</span><span class="sxs-lookup"><span data-stu-id="db41f-112">The output is the following, followed by a stack trace (not shown).</span></span>

```
December
January
System.ArgumentException: Month parameter out of range.
```

## <a name="see-also"></a><span data-ttu-id="db41f-113">请参阅</span><span class="sxs-lookup"><span data-stu-id="db41f-113">See also</span></span>

- [<span data-ttu-id="db41f-114">异常处理</span><span class="sxs-lookup"><span data-stu-id="db41f-114">Exception Handling</span></span>](index.md)
- [<span data-ttu-id="db41f-115">异常类型</span><span class="sxs-lookup"><span data-stu-id="db41f-115">Exception Types</span></span>](exception-types.md)
- [<span data-ttu-id="db41f-116">异常：`try...with` 表达式</span><span class="sxs-lookup"><span data-stu-id="db41f-116">Exceptions: The `try...with` Expression</span></span>](the-try-with-expression.md)
- [<span data-ttu-id="db41f-117">异常：`try...finally` 表达式</span><span class="sxs-lookup"><span data-stu-id="db41f-117">Exceptions: The `try...finally` Expression</span></span>](the-try-finally-expression.md)
- [<span data-ttu-id="db41f-118">异常：`raise` 函数</span><span class="sxs-lookup"><span data-stu-id="db41f-118">Exceptions: the `raise` Function</span></span>](the-raise-function.md)
- [<span data-ttu-id="db41f-119">异常：`failwith` 函数</span><span class="sxs-lookup"><span data-stu-id="db41f-119">Exceptions: The `failwith` Function</span></span>](the-failwith-function.md)
