---
title: '&#39;引发&#39;语句不能省略操作数外部&#39;捕获&#39;语句中还是在&#39;Finally&#39;语句'
ms.date: 07/20/2015
f1_keywords:
- vbc30666
- bc30666
helpviewer_keywords:
- BC30666
ms.assetid: a208a6ea-0e36-4bf1-8984-4de1a0e38a2a
ms.openlocfilehash: e426e0d7af685fae82d8dc64a95803bdacb543e0
ms.sourcegitcommit: 6eac9a01ff5d70c6d18460324c016a3612c5e268
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 09/15/2018
ms.locfileid: "45645874"
---
# <a name="39throw39-statement-cannot-omit-operand-outside-a-39catch39-statement-or-inside-a-39finally39-statement"></a>&#39;引发&#39;语句不能省略操作数外部&#39;捕获&#39;语句中还是在&#39;Finally&#39;语句
`Throw` 语句外的 `Catch` 语句必须提供异常对象的名称。  
  
 **错误 ID：** BC30666  
  
## <a name="to-correct-this-error"></a>更正此错误  
  
1.  指定派生自 `System.Exception`的异常对象的名称。  
  
2.  重构代码，以便 `Throw` 语句位于 `Catch` 块中。  
  
## <a name="see-also"></a>请参阅  
 [Throw 语句](../../visual-basic/language-reference/statements/throw-statement.md)  
 [Try...Catch...Finally 语句](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)  
 [在 Visual Basic 中的异常类](https://msdn.microsoft.com/library/9aac396f-34ca-4afb-8e6c-e523cb690ba9)  
 [异常和 Visual Basic 中的错误处理](https://msdn.microsoft.com/library/3e351e73-cf23-40ab-8b60-05794160529e)
